import React from "react";
import { ScenarioGroupContent } from "./ScenarioGroupContent.jsx";
import { ScenarioGroupHeader } from "./ScenarioGroupHeader.jsx";
import { ScenarioGroupHeadingSearchPanel } from "./ScenarioGroupHeadingSearchPanel.jsx";

export function ScenarioGroupSection({
  group,
  groupIndex,
  isExpanded,
  visibleItems,
  remaining,
  groupDone,
  groupDoneCount,
  groupTotalSegments,
  groupCompletionPercent,
  groupLoading,
  headingRuQuery,
  headingEnQuery,
  isHeadingSearchOpen,
  canExportGroupXml,
  headingRuEngines,
  headingEnEngines,
  headingTranslateLoading,
  handleToggleGroupDone,
  handleAddLinksBlock,
  docId,
  loading,
  handleAiHelp,
  handleEditThemeTags,
  toggleHeadingSearch,
  handleExport,
  toggleGroup,
  handleSearch,
  handleHeadingEnglishQueryChange,
  translateHeadingQuery,
  handleShowMore,
  LinksCardComponent,
  SegmentCardComponent,
  handleLinkAdd,
  handleLinkUpdate,
  handleLinkRemove,
  handleOpenSegmentScreenshotMode,
  handleDownloadMedia,
  isMediaDownloadBusy,
  isMediaDownloadSupported,
  isMediaDownloaded,
  config,
  mediaFiles,
  updateSegment,
  updateVisual,
  updateSearch,
  handleQuoteChange,
  handleInsertAfter,
  handleRemoveSegment,
  handleClearSearch,
  handleGenerateSearch,
  searchLoading,
  handleSearchToggle,
  segmentResearchRuns,
  segmentResearchHistory,
  segmentResearchLoading,
  handleRunSegmentResearch,
  handleSelectSegmentResearchRun,
  handleApplySegmentResearch,
  handlePromoteSegmentResearchBundle,
  handleCopySegmentResearchBrief,
  handleOpenResearchWorkspace,
  linkedReleaseSegmentIds,
  selectedReleaseDetail,
  linkedReleaseSnapshotBySegmentId,
  handleOpenReleaseFromSegment,
  handleUseLinkedReleasePrimary,
  handlePromoteLinkedReleasePrimaryPair,
  handlePromoteLinkedReleaseBackupPair,
  handleUseLinkedReleaseBackup,
  handleCopy,
  handleToggleSegmentDone
}) {
  return (
    <div key={`${group.id}-${groupIndex}`} className="segment-group">
      <ScenarioGroupHeader
        group={group}
        groupDone={groupDone}
        groupDoneCount={groupDoneCount}
        groupTotalSegments={groupTotalSegments}
        groupCompletionPercent={groupCompletionPercent}
        handleToggleGroupDone={handleToggleGroupDone}
        handleAddLinksBlock={handleAddLinksBlock}
        docId={docId}
        loading={loading}
        groupLoading={groupLoading}
        handleAiHelp={handleAiHelp}
        handleEditThemeTags={handleEditThemeTags}
        toggleHeadingSearch={toggleHeadingSearch}
        headingRuQuery={headingRuQuery}
        headingEnQuery={headingEnQuery}
        handleExport={handleExport}
        canExportGroupXml={canExportGroupXml}
        isExpanded={isExpanded}
        toggleGroup={toggleGroup}
      />
      {isHeadingSearchOpen ? (
        <ScenarioGroupHeadingSearchPanel
          groupId={group.id}
          headingRuQuery={headingRuQuery}
          headingEnQuery={headingEnQuery}
          headingRuEngines={headingRuEngines}
          headingEnEngines={headingEnEngines}
          handleSearch={handleSearch}
          handleHeadingEnglishQueryChange={handleHeadingEnglishQueryChange}
          translateHeadingQuery={translateHeadingQuery}
          headingTranslateLoading={headingTranslateLoading}
        />
      ) : null}
      {isExpanded ? (
        <ScenarioGroupContent
          group={group}
          visibleItems={visibleItems}
          remaining={remaining}
          handleShowMore={handleShowMore}
          LinksCardComponent={LinksCardComponent}
          SegmentCardComponent={SegmentCardComponent}
          handleLinkAdd={handleLinkAdd}
          handleLinkUpdate={handleLinkUpdate}
          handleLinkRemove={handleLinkRemove}
          handleOpenSegmentScreenshotMode={handleOpenSegmentScreenshotMode}
          handleDownloadMedia={handleDownloadMedia}
          isMediaDownloadBusy={isMediaDownloadBusy}
          isMediaDownloadSupported={isMediaDownloadSupported}
          isMediaDownloaded={isMediaDownloaded}
          config={config}
          docId={docId}
          mediaFiles={mediaFiles}
          updateSegment={updateSegment}
          updateVisual={updateVisual}
          updateSearch={updateSearch}
          handleQuoteChange={handleQuoteChange}
          handleInsertAfter={handleInsertAfter}
          handleRemoveSegment={handleRemoveSegment}
          handleClearSearch={handleClearSearch}
          handleGenerateSearch={handleGenerateSearch}
          searchLoading={searchLoading}
          handleSearchToggle={handleSearchToggle}
          handleSearch={handleSearch}
          segmentResearchRuns={segmentResearchRuns}
          segmentResearchHistory={segmentResearchHistory}
          segmentResearchLoading={segmentResearchLoading}
          handleRunSegmentResearch={handleRunSegmentResearch}
          handleSelectSegmentResearchRun={handleSelectSegmentResearchRun}
          handleApplySegmentResearch={handleApplySegmentResearch}
          handlePromoteSegmentResearchBundle={handlePromoteSegmentResearchBundle}
          handleCopySegmentResearchBrief={handleCopySegmentResearchBrief}
          handleOpenResearchWorkspace={handleOpenResearchWorkspace}
          linkedReleaseSegmentIds={linkedReleaseSegmentIds}
          selectedReleaseDetail={selectedReleaseDetail}
          linkedReleaseSnapshotBySegmentId={linkedReleaseSnapshotBySegmentId}
          handleOpenReleaseFromSegment={handleOpenReleaseFromSegment}
          handleUseLinkedReleasePrimary={handleUseLinkedReleasePrimary}
          handlePromoteLinkedReleasePrimaryPair={handlePromoteLinkedReleasePrimaryPair}
          handlePromoteLinkedReleaseBackupPair={handlePromoteLinkedReleaseBackupPair}
          handleUseLinkedReleaseBackup={handleUseLinkedReleaseBackup}
          handleCopy={handleCopy}
          handleToggleSegmentDone={handleToggleSegmentDone}
        />
      ) : null}
    </div>
  );
}
